[project]
name = "pdf2markdownbyqwenvl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.76.0",
    "pymupdf>=1.25.5",
]
